{% set version = "0.4.5" %}

package:
  name: r-ggfortify
  version: {{ version }}

source:
  fn: ggfortify_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ggfortify_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ggfortify/ggfortify_{{ version }}.tar.gz
  sha256: 359b75e337b15e938fd01a803f7fea82c7843b817e60223ff89f91f1ee8c0fd7

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dplyr >=0.3
    - r-ggplot2 >=2.0.0
    - r-gridextra
    - r-scales
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-dplyr >=0.3
    - r-ggplot2 >=2.0.0
    - r-gridextra
    - r-scales
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('ggfortify')"  # [not win]
    - "\"%R%\" -e \"library('ggfortify')\""  # [win]

about:
  home: https://github.com/sinhrks/ggfortify
  license: GPL-2
  summary: Unified plotting tools for statistics commonly used, such as GLM, time series, PCA
    families, clustering and survival analysis. The package offers a single plotting
    interface for these analysis results and plots in a unified style using 'ggplot2'.
  license_family: GPL2

extra:
  recipe-maintainers:
    - ocefpaf
