{% set version = '0.4.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggfortify
  version: {{ version|replace("-", "_") }}

source:
  fn: ggfortify_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggfortify_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggfortify/ggfortify_{{ version }}.tar.gz
  sha256: 359b75e337b15e938fd01a803f7fea82c7843b817e60223ff89f91f1ee8c0fd7

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.3
    - r-ggplot2 >=2.0.0
    - r-gridextra
    - r-scales
    - r-stringr
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-dplyr >=0.3
    - r-ggplot2 >=2.0.0
    - r-gridextra
    - r-scales
    - r-stringr
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('ggfortify')"           # [not win]
    - "\"%R%\" -e \"library('ggfortify')\""  # [win]

about:
  home: https://github.com/sinhrks/ggfortify
  license: GPL-2
  summary: Unified plotting tools for statistics commonly used, such as GLM, time series, PCA
    families, clustering and survival analysis. The package offers a single plotting
    interface for these analysis results and plots in a unified style using 'ggplot2'.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
