travis:
  secure:
    BINSTAR_TOKEN: p7DvuZ+619JHEaRjC85N+16s5hOhVi1Kd8BphNV3mTlswRSq2Y8Opd+WFd9eJgHVDFV/PMKXJArpyftkyrPixK6ObXNAaslz7HX5gBjncy0N+wT0qE5/yxpYe43ig9a0xTFDl2bacC6t2wEGm2GV863rFY1zgrFYBOp7JvTqe+2lzb/q5xBOmynCIH4KJZ8IwZwu6podLwBgbiDp8bupC3T0ZHymChVV/F8WwoLnwPDV3fvFi5lNpuLOgMpJP3QKmkCoH1/0PJDjzjqzrPiNjLUt4gSxKF0k7rdEPPuYDWnnJgV4XNHW/cc1IvuAF+tD3rb09PXqODZ8UnH6wDddpzsGbm8HWa2l3jvQctOM7xNu+Xkn8OISRShJ6iM2m+vGXjvTDkrlHyhVYCQDu6tjwqan2+/bPRqxNlwf0o79vrm2kJPvXvP2OGbqYQ+WXEeXrwlSnrAWjHEtd51+0uX2q+V8n7lHIvWlm97exy7WVcSYVwm9wlQDbimiuFrmYoLzZ5ZyElugOEOqjYwuiIyD080ECYvVwWmR3Yb5v7jp1jhWVyi8iKOyKIHSaZ9J8G0nSeizn5Bm7v9HYfMwHGRV4IlL5mwWmxMhl59kDhsCYx5hAD4NwSEPiRdTsaT/VPHT/OQwC2iTIS+uN/wglgoXkyqmKVwZ1km1gNOzcVLvpug=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
