travis:
  secure:
    BINSTAR_TOKEN: PqUtLLRWoF+1oLeyHUOuWek+TGwZAxCI0+fATYAZwPnNQ6G4JiI2aYVFyAk9QSLzXzyIadolP7mmemzWznWzkHJQLQX22mFtahGTv1U5zjh2EbkYR+GUvgc0A8DvCMPz6iW5oveOCQNZZY8G4V3RTfGO6uwaQn51QsioeV4xhmurAHGKG7tEl8sUoiboFzRrXKoPOQIgnDv0Srjcoq7jK1yzzXK5MrkFy4/4mvzpNg1BWyKbJ88W3F9zDJFdS+sKMp5zl8p70/KsUhaxu/v4JTAPp3zCm/wAO4dyTaNpouRyJkoatMVdfxhhEtzDcyUVbCes/fMvk9x+ALhDZi7+O0qcibEc7uZYXCrArXBpo3x6F9P8cPfBwKGdjJQcNe82tk0SZMYgNE5yRN4WxeejvF886ugUtp94HA4xW/gpVQW36aKB6+9+wrhmewLOi6inACBNzeJ5yM4nMoeJbHs+jZNg0fCtEkRZQfN1LXMxeTMwCaa2b/HwwlC/GgC/Tl+tyqJdJ4ZI7soFNz/LFCtbe+FLpAY5O+2+n20iXs+He6uBUKFtec4o3GpFlLgD0Y/dapgZR/T2iqJXkZ9AMfSKASB8W2IEC81k8oabW97xost6OKDNVE0T8LEcx701knuCurZg6MqtlIilymh1RBbNExOtJDdH8iRUuM6dwmy7YnE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
