travis:
  secure:
    BINSTAR_TOKEN: AC2LG2w9AroEEZsrIlOafeILSYp0OIRzxlcq4zxmw89V/DjaKMW/0E7EcPlDVMZxDWcuZRwybUj+sfJX4AAZIdB9XzJlGGHbJ5j5wlXjz60A9g8wE1vmLJa23pfztHCaD9BAnJmL6g4faZI6PZq74VgLPV6cG/lbVSrRmNEAuDG8qKSRK23+8Dkm4r0dqZaIY7CSgUhRIpz1foOrpTg6y7OiEOJGZwwUfpAhSV6Yeebx+uoLApsu+KolnX3xKxi4lqbMOfvhuj4+PP+ajMTzswnsStqTYOdYfsvD40K48E1dhTFHYRpWgeofaUyLPPhUZD0QHOJYUH5gBdaov/vvjx3XwtRm+v8Gi6E1KPpnCL04AaI5N2C57rMJeREBKfIQ9vw/z0nL9h77YFVa1pJE73GPxuCIHtLB7KGzSJUZN7k2H+DnzlILE/SuQPqWu9F46c3Y27sHm4brzyu9HGmK4s0LQLpbUBCkX2dfrfiRhfzgb6oqGl0Py0/edJeecRemjUSb9xmgdaOVNqOsOxcoZrl67qtm3Pao2ATk8M6FynzSIyAysg1UKgnKq7DoqknPqJU1YCE5Kn9VNQHqa5Ytmy4SQoK8/zUODJxYaFmozldGIJr6FDp9dr8IzI3TnUiRcuAmk39gZjK7WGOTuAE6eYAOC0fvyWqmKfeXUxiMksU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
