travis:
  secure:
    BINSTAR_TOKEN: DwkwhGALfnQsq4WA5JC66ejwfnjP5VtjlK/h3Yt5NDVZidCsDUlK06Sl3yI5i/bwMswTqoaogKSkMzrmZWAPw0AMjj+8hFX8WWqCmlXpV9k0pjTyq86UKMD18MGTG7dIO+8FaWqVzkPm4qV5PhipNLwHqd3P8KCiiFUv+6nDTZhhA0sxY9ZPIn1PFDTvGH4FlZxTXmj5+pCp+GH8ORerxGoip4L/F3qxQnLRveqdAcRAyfOSqRh63lLskTaFnjQHxNkCa14LTbh3pK16yji3lQ/uQg3yRwaVHBVDNFEj9szHnU9k07VWs7SMC0TUlwV88u61vttLqk6pRqci0JhiMiFUtxeg4EiYupx2d+c+Zpj2FhFSekokWPGG5C808NS+GJzy8wdAkTLC/vizkx3zFaEk8Dx0cIWeEhI8LRDnvOO3JC/fV6+KVjfnHdioTrrMf81YQM6ec2wiyF/hoTMjB0LLg+r0G5TcAs1TPZtZ2e/Ur3XWZZeOBLOoAKJKCNnov9p0DBjw6vLBtLgwLTS47PzPOh2Ydex/CCBBsLcXtBt1HU75o1p/BILIR/6w6dsVU6UH0vHsK/B9uae38CpD2aZDhHdZUPDvli2vgcr5NYSqTV7YP4vCorJWj15UIrKbQ+zKQd0hpStQIPkBa2UKAKSfNrq7r0jc9sPgQfrgjS8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
